from documator.frontmatter import partition
from documator.manifest import TemplatePath
from documator.parsing import Markdown


# Below any leading frontmatter, so passing an Obsidian note through keeps its YAML.
def annotated(source: Markdown, template: TemplatePath) -> Markdown:
    split = partition(source)
    notice = (
        f"<!-- Generated by documator from {template} "
        "— edit the template, not this file. -->\n"
    )
    return Markdown(f"{split.preamble}{notice}{split.body}")
