from pathlib import Path

from inline_snapshot import snapshot

from documator.domain import InputDir, OutputDir, TimeoutSeconds
from documator.render import render
from documator.skills import skills
from documator.tree_layout import TreeLayout, build_tree


def _render(input_dir: Path, output_dir: Path) -> int:
    return render(InputDir(input_dir), OutputDir(output_dir), TimeoutSeconds(10.0))


def _skills(input_dir: Path, output_dir: Path) -> int:
    return skills(InputDir(input_dir), OutputDir(output_dir), TimeoutSeconds(10.0))


def test_an_attachment_link_follows_the_flattened_bundle(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              guides
                @plan
                  SKILL.md | see [[diagram.png]] for the shape\\n
                  assets
                    diagram.png | not really a png\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "plan" / "SKILL.md").read_text() == snapshot("""\
---
name: plan
description: plan
---
<!-- Generated by documator from guides/@plan/SKILL.md — edit the template, not this file. -->
see [diagram](assets/diagram.png) for the shape
""")


def test_an_attachment_outside_the_bundle_has_nowhere_to_land(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              assets
                diagram.png | not really a png\\n
              guides
                @plan
                  SKILL.md | see [[diagram.png]] for the shape\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "plan" / "SKILL.md").read_text() == snapshot("""\
---
name: plan
description: plan
---
<!-- Generated by documator from guides/@plan/SKILL.md — edit the template, not this file. -->
see [[diagram.png]] [documator: link to assets/diagram.png, which this run does not emit] for the shape
""")


# The text came to rest in the host, so the path has to work from there rather than from
# the note that lent it.
def test_a_link_inside_a_transclusion_lands_from_the_host(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              _partial.md | see [[diagram.png]] for the shape\\n
              guides
                @plan
                  SKILL.md | ![[_partial]]\\n
                  assets
                    diagram.png | not really a png\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "plan" / "SKILL.md").read_text() == snapshot("""\
---
name: plan
description: plan
---
<!-- Generated by documator from guides/@plan/SKILL.md — edit the template, not this file. -->
see [diagram](assets/diagram.png) for the shape

""")


def test_a_skill_link_is_an_invocation_in_the_flat_layout_too(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              @review.md | run [[@grill]] first\\n
              @grill.md | # Grill\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "review" / "SKILL.md").read_text() == snapshot("""\
---
name: review
description: review
---
<!-- Generated by documator from @review.md — edit the template, not this file. -->
run `/grill` first
""")


def test_an_alias_and_a_fragment_reach_an_attachment_together(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | see [[diagram.png#zoom|the shape]] here\\n
              assets
                diagram.png | not really a png\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
see [the shape](assets/diagram.png#zoom) here
""")


def test_a_link_a_command_prints_is_data_rather_than_a_link(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ```\\n!echo '[[Tracer bullet]]'\\n```\\n
              Tracer bullet.md | a thin vertical slice\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    # Spelled with escapes rather than snapshotted: what a command prints is neutralized
    # on the way out, so the brackets it survives as are holding zero-width spaces.
    assert (tmp_path / "out" / "index.md").read_text().splitlines()[2] == (
        "[\u200b[Tracer bullet]\u200b]"
    )


def test_a_link_to_an_attachment_emits_a_path_to_where_it_landed(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              docs
                index.md | see [[diagram.png]] for the shape\\n
              assets
                diagram.png | not really a png\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "docs" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from docs/index.md — edit the template, not this file. -->
see [diagram](../assets/diagram.png) for the shape
""")


def test_a_link_inside_a_fence_is_quoted_code(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ```\\n[[Tracer bullet]]\\n```\\n
              Tracer bullet.md | a thin vertical slice\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
```
[[Tracer bullet]]
```
""")


def test_a_link_inside_a_code_span_is_quoted_code(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | write `[[Tracer bullet]]` to link\\n
              Tracer bullet.md | a thin vertical slice\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
write `[[Tracer bullet]]` to link
""")


def test_a_link_to_a_skill_emits_an_invocation(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | run [[@grill]] first\\n
              guides
                @grill.md | # Grill\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
run `/grill` first
""")


def test_an_alias_cannot_relabel_a_skill_invocation(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | run [[@grill|the grill]] first\\n
              @grill.md | # Grill\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
run `/grill` first
""")


def test_the_inert_prefix_never_reaches_the_reader(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | see [[_Tracer bullet]] for more\\n
              _Tracer bullet.md | a thin vertical slice\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
see Tracer bullet for more
""")


def test_a_fragment_rides_along_with_the_name(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | see [[Tracer bullet#Details]] for more\\n
              Tracer bullet.md | # Details\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
see Tracer bullet#Details for more
""")


def test_a_fragment_rides_along_behind_an_alias_too(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | see [[Tracer bullet#Details|the details]] for more\\n
              Tracer bullet.md | # Details\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
see the details#Details for more
""")


def test_frontmatter_is_left_alone_by_the_link_resolver(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ---\\ntitle: "[[Tracer bullet]]"\\n---\\nbody [[Tracer bullet]]\\n
              Tracer bullet.md | a thin vertical slice\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
---
title: "[[Tracer bullet]]"
---
<!-- Generated by documator from index.md — edit the template, not this file. -->
body Tracer bullet
""")


def test_an_alias_replaces_the_name_of_a_linked_note(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | we fire [[Tracer bullet|tracer bullets]] here\\n
              Tracer bullet.md | a thin vertical slice\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
we fire tracer bullets here
""")


def test_a_link_matching_no_note_is_left_in_place_and_fails_the_content(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | see [[Missing]] for more\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
see [[Missing]] [documator: no note matches link "Missing"] for more
""")


def test_a_link_matching_several_notes_is_left_in_place_and_fails_the_content(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | see [[Shared]] for more\\n
              one
                Shared.md | first\\n
              two
                Shared.md | second\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
see [[Shared]] [documator: link "Shared" matches one/Shared.md, two/Shared.md] for more
""")


def test_a_link_to_a_note_emits_its_name(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | see [[Tracer bullet]] for more\\n
              glossary
                Tracer bullet.md | a thin vertical slice\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
see Tracer bullet for more
""")
