import os
import re
import subprocess
from pathlib import Path

from documator.execution import Command
from documator.tree_layout import TreeLayout, assert_tree


def _try_it_block(readme: Path) -> Command:
    block = re.search(
        r"### Try it\n+```sh\n(?P<commands>.*?)```", readme.read_text(), re.DOTALL
    )
    assert block is not None, "README has no fenced sh block under '### Try it'"
    return Command(block["commands"])


def test_readme_try_it_block_mirrors_and_compiles_both_template_forms(
    tmp_path: Path,
) -> None:
    repo = Path(__file__).parents[2]
    # uv discovers no project from a tempdir, so point it back at this checkout.
    result = subprocess.run(
        _try_it_block(repo / "README.md"),
        shell=True,
        cwd=tmp_path,
        env={**os.environ, "UV_PROJECT": str(repo)},
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            guides
              review.md | <!-- Generated by documator from guides/review.md — edit the template, not this file. -->\\n# Review\\n\\nRead the diff before the description.\\n
              plan
                SKILL.md | ---\\ndescription: Plan a change\\n---\\n<!-- Generated by documator from guides/plan/SKILL.md — edit the template, not this file. -->\\n# Plan\\n
                references
                  spec.md | <!-- Generated by documator from guides/plan/references/spec.md — edit the template, not this file. -->\\n# Spec\\n
        """),
    )
    assert_tree(
        tmp_path / "compiled",
        TreeLayout("""
            plan
              SKILL.md | ---\\nname: plan\\ndescription: Plan a change\\n---\\n<!-- Generated by documator from guides/plan/SKILL.md — edit the template, not this file. -->\\n# Plan\\n
              references
                spec.md | <!-- Generated by documator from guides/plan/references/spec.md — edit the template, not this file. -->\\n# Spec\\n
            review
              SKILL.md | ---\\nname: review\\ndescription: review\\n---\\n<!-- Generated by documator from guides/review.md — edit the template, not this file. -->\\n# Review\\n\\nRead the diff before the description.\\n
        """),
    )
