import logging
from pathlib import Path

import pytest
from inline_snapshot import snapshot

from documator.domain import InputDir, OutputDir, TimeoutSeconds
from documator.engine import ConflictReason, Mode
from documator.render import render
from documator.tree_layout import TreeLayout, assert_tree, build_tree


def _render(input_dir: Path, output_dir: Path) -> int:
    return render(InputDir(input_dir), OutputDir(output_dir), TimeoutSeconds(10.0))


def _check(input_dir: Path, output_dir: Path) -> int:
    return render(
        InputDir(input_dir), OutputDir(output_dir), TimeoutSeconds(10.0), Mode.CHECK
    )


def test_the_skill_mark_is_stripped_from_the_mirrored_path(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              @grill.md | # Grill\\n
              @plan
                SKILL.md | # Plan\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            grill.md | <!-- Generated by documator from @grill.md — edit the template, not this file. -->\\n# Grill\\n
            plan
              SKILL.md | <!-- Generated by documator from @plan/SKILL.md — edit the template, not this file. -->\\n# Plan\\n
        """),
    )


def test_a_mark_where_no_skill_can_stand_is_refused_rather_than_mirrored(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              @diagram.png | not really a png\\n
              @plan
                SKILL.md | # Plan\\n
                @nested.md | # Nested\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            plan
              SKILL.md | <!-- Generated by documator from @plan/SKILL.md — edit the template, not this file. -->\\n# Plan\\n
        """),
    )


def test_two_sources_landing_on_one_mirrored_path_emit_neither(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              @grill.md | # Marked\\n
              grill.md | # Bare\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert_tree(tmp_path / "out", TreeLayout(""))


def test_mirrors_input_tree_verbatim(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
              sub
                nested.md | nested\\n
                data.csv | a,b\\n1,2\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            note.md | <!-- Generated by documator from note.md — edit the template, not this file. -->\\n# Note\\n
            sub
              nested.md | <!-- Generated by documator from sub/nested.md — edit the template, not this file. -->\\nnested\\n
              data.csv | a,b\\n1,2\\n
        """),
    )


def test_copies_binary_files_verbatim(tmp_path: Path) -> None:
    build_tree(tmp_path, TreeLayout("in\nout"))
    payload = bytes(range(256))
    (tmp_path / "in" / "image.png").write_bytes(payload)

    assert _render(tmp_path / "in", tmp_path / "out") == 0
    assert (tmp_path / "out" / "image.png").read_bytes() == payload


def test_a_tracked_output_this_run_no_longer_produces_is_pruned(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
              gone
                stale.md | stale\\n
            out
        """),
    )
    assert _render(tmp_path / "in", tmp_path / "out") == 0

    (tmp_path / "in" / "gone" / "stale.md").unlink()
    (tmp_path / "in" / "gone").rmdir()

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout(
            "note.md | <!-- Generated by documator from note.md"
            " — edit the template, not this file. -->\\n# Note\\n"
        ),
    )


def test_an_untracked_output_file_is_left_where_it_is(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
            out
              mine
                notes.md | mine\\n
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            note.md | <!-- Generated by documator from note.md — edit the template, not this file. -->\\n# Note\\n
            mine
              notes.md | mine\\n
        """),
    )


def test_an_untracked_file_at_a_target_path_blocks_the_write(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
            out
              note.md | mine\\n
        """),
    )

    with caplog.at_level(logging.ERROR, logger="documator"):
        assert _render(tmp_path / "in", tmp_path / "out") == 2

    assert_tree(tmp_path / "out", TreeLayout("note.md | mine\\n"))
    assert caplog.messages == snapshot(
        [
            "note.md: refusing to overwrite: not written by documator",
            "0 files, 0 warnings, 1 error",
            "note.md: refusing to overwrite: not written by documator",
        ]
    )


def test_an_untracked_file_where_a_parent_directory_belongs_blocks_the_write(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md
                inner.md | inner\\n
            out
              note.md | mine\\n
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 2

    assert_tree(tmp_path / "out", TreeLayout("note.md | mine\\n"))


def test_a_blocked_write_does_not_stop_the_rest_of_the_run(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              blocked.md | # Blocked\\n
              free.md | # Free\\n
            out
              blocked.md | mine\\n
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 2

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            blocked.md | mine\\n
            free.md | <!-- Generated by documator from free.md — edit the template, not this file. -->\\n# Free\\n
        """),
    )


def test_a_tracked_file_does_not_block_a_path_that_became_a_directory(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | note\\n
            out
        """),
    )
    assert _render(tmp_path / "in", tmp_path / "out") == 0

    (tmp_path / "in" / "note.md").unlink()
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md
                inner.md | inner\\n
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            note.md
              inner.md | <!-- Generated by documator from note.md/inner.md — edit the template, not this file. -->\\ninner\\n
        """),
    )


def test_a_tracked_directory_does_not_block_a_path_that_became_a_file(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md
                stale.md | stale\\n
            out
        """),
    )
    assert _render(tmp_path / "in", tmp_path / "out") == 0

    (tmp_path / "in" / "note.md" / "stale.md").unlink()
    (tmp_path / "in" / "note.md").rmdir()
    (tmp_path / "in" / "note.md").write_text("note\n")

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout(
            "note.md | <!-- Generated by documator from note.md"
            " — edit the template, not this file. -->\\nnote\\n"
        ),
    )


def test_the_notice_sits_below_a_notes_own_frontmatter(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | ---\\ntags: [a]\\n---\\n# Note\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "note.md").read_text() == snapshot("""\
---
tags: [a]
---
<!-- Generated by documator from note.md — edit the template, not this file. -->
# Note
""")


def test_copies_file_mode(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              run.sh | #!/bin/sh\\n
            out
        """),
    )
    (tmp_path / "in" / "run.sh").chmod(0o755)

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(tmp_path / "out", TreeLayout("run.sh | #!/bin/sh\\n"))
    assert (tmp_path / "out" / "run.sh").stat().st_mode & 0o777 == 0o755


def test_renders_files_in_sorted_path_order(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
              sub
                nested.md | nested\\n
                data.csv | a,b\\n1,2\\n
            out
        """),
    )

    with caplog.at_level(logging.INFO, logger="documator"):
        assert _render(tmp_path / "in", tmp_path / "out") == 0

    rendered = [
        record.message.removeprefix("rendered ")
        for record in caplog.records
        if record.message.startswith("rendered ")
    ]
    assert rendered == sorted(rendered)
    assert rendered == ["note.md", "sub/data.csv", "sub/nested.md"]


def test_identical_input_and_output_leaves_the_tree_untouched(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
        """),
    )

    with caplog.at_level(logging.ERROR, logger="documator"):
        assert _render(tmp_path / "in", tmp_path / "in") == 2

    assert ConflictReason.IDENTICAL in caplog.text
    assert_tree(tmp_path / "in", TreeLayout("note.md | # Note\\n"))


def test_output_nested_in_input_leaves_the_tree_untouched(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
              out
        """),
    )

    with caplog.at_level(logging.ERROR, logger="documator"):
        assert _render(tmp_path / "in", tmp_path / "in" / "out") == 2

    assert ConflictReason.OUTPUT_NESTED_IN_INPUT in caplog.text
    assert_tree(
        tmp_path / "in",
        TreeLayout("""
            note.md | # Note\\n
            out
        """),
    )


def test_an_input_nested_in_the_output_renders_beside_itself(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
        """),
    )

    assert _render(tmp_path / "in", tmp_path) == 0

    assert_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
            note.md | <!-- Generated by documator from note.md — edit the template, not this file. -->\\n# Note\\n
        """),
    )


def test_a_nested_input_is_never_pruned_by_the_run_that_reads_it(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
        """),
    )
    assert _render(tmp_path / "in", tmp_path) == 0

    (tmp_path / "in" / "note.md").write_text("# Renamed\n")

    assert _render(tmp_path / "in", tmp_path) == 0

    assert (tmp_path / "in" / "note.md").read_text() == "# Renamed\n"


def test_empty_input_directory_produces_an_empty_output(tmp_path: Path) -> None:
    build_tree(tmp_path, TreeLayout("in\nout"))

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(tmp_path / "out", TreeLayout(""))


def test_executable_block_is_replaced_by_its_output(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n\\n```\\n!echo hi\\n```\\n\\nafter\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "note.md").read_text() == (
        "<!-- Generated by documator from note.md — edit the template, not this file. -->\n"
        "# Note\n\n```\nhi\n```\n\nafter\n"
    )


def test_executable_span_is_replaced_inside_its_sentence(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | The answer is `!echo 42` today.\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "note.md").read_text() == snapshot(
        """\
<!-- Generated by documator from note.md — edit the template, not this file. -->
The answer is `42` today.
"""
    )


def test_failing_span_fails_the_run_and_keeps_rendering(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              a.md | value `!exit 3` here\\n
              b.md | value `!echo ok` here\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "a.md").read_text() == snapshot(
        """\
<!-- Generated by documator from a.md — edit the template, not this file. -->
value `[documator: exit 3]` here
"""
    )
    assert (tmp_path / "out" / "b.md").read_text() == snapshot("""\
<!-- Generated by documator from b.md — edit the template, not this file. -->
value `ok` here
""")


def test_span_with_multi_line_output_becomes_a_fence_in_the_document(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | Lines:`!echo a; echo b` done.\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "note.md").read_text() == snapshot("""\
<!-- Generated by documator from note.md — edit the template, not this file. -->
Lines:
```
a
b
```
 done.
""")


def test_span_runs_beside_its_own_file(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              sub
                note.md | says `!cat sibling.txt`\\n
                sibling.txt | neighbour\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "sub" / "note.md").read_text() == snapshot(
        """\
<!-- Generated by documator from sub/note.md — edit the template, not this file. -->
says `neighbour`
"""
    )


def test_block_runs_beside_its_own_file(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              sub
                note.md | ```\\n!cat sibling.txt\\n```\\n
                sibling.txt | neighbour\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "sub" / "note.md").read_text() == snapshot("""\
<!-- Generated by documator from sub/note.md — edit the template, not this file. -->
```
neighbour
```
""")


def test_non_markdown_file_is_copied_without_executing_its_blocks(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              recipe.txt | ```\\n!echo hi\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "recipe.txt").read_text() == "```\n!echo hi\n```\n"


def test_failing_block_embeds_its_output_and_the_run_continues(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              a.md | ```\\n!echo partial; exit 3\\n```\\n
              b.md | ```\\n!echo second\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "a.md").read_text() == (
        "<!-- Generated by documator from a.md — edit the template, not this file. -->\n"
        "```\npartial\n[documator: exit 3]\n```\n"
    )
    assert (tmp_path / "out" / "b.md").read_text() == (
        "<!-- Generated by documator from b.md — edit the template, not this file. -->\n"
        "```\nsecond\n```\n"
    )


def test_timeout_bounds_every_block(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | ```\\n!sleep 5\\n```\\n
            out
        """),
    )

    exit_code = render(
        InputDir(tmp_path / "in"), OutputDir(tmp_path / "out"), TimeoutSeconds(0.3)
    )

    assert exit_code == 1
    assert "timed out" in (tmp_path / "out" / "note.md").read_text()


def test_structural_error_is_marked_in_place_and_fails_the_run(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | ```\\n!echo one\\n!echo two\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 1

    rendered = (tmp_path / "out" / "note.md").read_text()
    assert "!echo one" in rendered
    assert "more than one command line in a single block" in rendered


def test_embedded_output_cannot_inject_links_or_tags(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | ```\\n!echo '![[Note]] [[Other]] #tag'\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    rendered = (tmp_path / "out" / "note.md").read_text()
    assert "[[" not in rendered
    assert "]]" not in rendered
    assert "#tag" not in rendered
    assert "Note" in rendered


def test_non_ascii_content_round_trips(tmp_path: Path) -> None:
    build_tree(tmp_path, TreeLayout("in\nout"))
    (tmp_path / "in" / "note.md").write_text("blåbær — 日本\n", encoding="utf-8")

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "note.md").read_text(encoding="utf-8") == (
        "<!-- Generated by documator from note.md — edit the template, not this file. -->\n"
        "blåbær — 日本\n"
    )


def test_undecodable_command_output_does_not_abort_the_render(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | ```\\n!printf '\\\\xff'; echo ok\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert "ok" in (tmp_path / "out" / "note.md").read_text(encoding="utf-8")


def test_uppercase_markdown_extension_is_parsed(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              NOTE.MD | ```\\n!echo hi\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "NOTE.MD").read_text() == (
        "<!-- Generated by documator from NOTE.MD — edit the template, not this file. -->\n"
        "```\nhi\n```\n"
    )


def test_logs_each_executed_block_with_its_file(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              sub
                note.md | ```\\n!echo hi\\n```\\n
            out
        """),
    )

    with caplog.at_level(logging.INFO, logger="documator"):
        assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert "executing echo hi in sub/note.md" in caplog.text
    assert "rendered sub/note.md" in caplog.text


def test_logs_a_failing_block_where_it_arises(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              sub
                note.md | ```\\n!false\\n```\\n
            out
        """),
    )

    with caplog.at_level(logging.ERROR, logger="documator"):
        assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert caplog.messages == snapshot(
        [
            "sub/note.md: false: exit 1",
            "1 file, 0 warnings, 1 error",
            "sub/note.md: false: exit 1",
        ]
    )


def test_the_run_ends_with_a_summary_that_repeats_its_errors_last(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | ```\\n!false\\n```\\n
              other.md | # Other\\n
            out
        """),
    )

    with caplog.at_level(logging.INFO, logger="documator"):
        assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert [
        (record.levelname, record.message) for record in caplog.records
    ] == snapshot(
        [
            ("INFO", "executing false in note.md"),
            ("ERROR", "note.md: false: exit 1"),
            ("INFO", "rendered note.md"),
            ("INFO", "rendered other.md"),
            ("ERROR", "2 files, 0 warnings, 1 error"),
            ("ERROR", "note.md: false: exit 1"),
        ]
    )


def test_a_clean_run_ends_with_a_summary_at_info(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(tmp_path, TreeLayout("in\n  note.md | # Note\\n\nout"))

    with caplog.at_level(logging.INFO, logger="documator"):
        assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert [
        (record.levelname, record.message) for record in caplog.records
    ] == snapshot(
        [("INFO", "rendered note.md"), ("INFO", "1 file, 0 warnings, 0 errors")]
    )


def test_declared_variable_expands_in_a_later_command(tmp_path: Path) -> None:
    build_tree(tmp_path, TreeLayout("in\nout"))
    (tmp_path / "in" / "note.md").write_text("""```
!var greet = echo hello
```
```
!{{greet}} world
```
""")

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "note.md").read_text() == snapshot("""\
<!-- Generated by documator from note.md — edit the template, not this file. -->
```
hello world
```
""")


def test_declaration_composes_an_earlier_variable(tmp_path: Path) -> None:
    build_tree(tmp_path, TreeLayout("in\nout"))
    (tmp_path / "in" / "note.md").write_text("""```
!var base = echo
```
```
!var greet = {{base}} hello
```
```
!{{greet}}
```
""")

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "note.md").read_text() == snapshot("""\
<!-- Generated by documator from note.md — edit the template, not this file. -->
```
hello
```
""")


def test_declared_variable_expands_in_a_later_span(tmp_path: Path) -> None:
    build_tree(tmp_path, TreeLayout("in\nout"))
    (tmp_path / "in" / "note.md").write_text("""```
!var greet = echo hello
```
It says `!{{greet}} world` here.
""")

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "note.md").read_text() == snapshot(
        """\
<!-- Generated by documator from note.md — edit the template, not this file. -->
It says `hello world` here.
"""
    )


def test_undefined_reference_in_a_span_hands_back_its_source_on_one_line(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | It says `!echo {{missing}}` here.\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "note.md").read_text() == snapshot(
        """\
<!-- Generated by documator from note.md — edit the template, not this file. -->
It says `!echo {{missing}}` [documator: undefined variable missing] here.
"""
    )


def test_var_in_a_span_is_a_command_not_a_declaration(tmp_path: Path) -> None:
    build_tree(tmp_path, TreeLayout("in\nout"))
    (tmp_path / "in" / "note.md").write_text("""Declared `!var greet = hi` inline.
Used `!echo {{greet}}` after.
""")

    assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert "undefined variable greet" in (tmp_path / "out" / "note.md").read_text()


def test_undefined_reference_hands_back_the_fence_without_running_it(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | ```\\n!echo {{missing}}\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "note.md").read_text() == snapshot("""\
<!-- Generated by documator from note.md — edit the template, not this file. -->
```
!echo {{missing}}
```

[documator: undefined variable missing]
""")


def test_reference_before_its_declaration_is_undefined(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | ```\\n!echo {{greet}}\\n```\\n```\\n!var greet = hi\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "note.md").read_text() == snapshot("""\
<!-- Generated by documator from note.md — edit the template, not this file. -->
```
!echo {{greet}}
```

[documator: undefined variable greet]
""")


def test_redeclaring_a_variable_fails_the_render(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | ```\\n!var greet = one\\n```\\n```\\n!var greet = two\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "note.md").read_text() == snapshot("""\
<!-- Generated by documator from note.md — edit the template, not this file. -->
```
!var greet = two
```

[documator: variable greet is already declared]
""")


def test_declaration_without_a_value_fails_the_render(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | ```\\n!var greet =\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "note.md").read_text() == snapshot("""\
<!-- Generated by documator from note.md — edit the template, not this file. -->
```
!var greet =
```

[documator: variable declaration has no value]
""")


def test_a_declaration_does_not_reach_into_a_transclusion(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | ```\\n!var greet = echo hi\\n```\\n![[partial]]\\n
              partial.md | ```\\n!{{greet}}\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "note.md").read_text() == snapshot("""\
<!-- Generated by documator from note.md — edit the template, not this file. -->
```
!{{greet}}
```

[documator: undefined variable greet]

""")


def test_a_declaration_inside_a_transclusion_does_not_leak_out(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | ![[partial]]\\n```\\n!{{greet}}\\n```\\n
              partial.md | ```\\n!var greet = echo hi\\n```\\n```\\n!{{greet}}\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "note.md").read_text() == snapshot("""\
<!-- Generated by documator from note.md — edit the template, not this file. -->
```
hi
```

```
!{{greet}}
```

[documator: undefined variable greet]
""")


def test_check_reports_a_missing_output_and_writes_nothing(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
            out
        """),
    )

    with caplog.at_level(logging.INFO, logger="documator"):
        assert _check(tmp_path / "in", tmp_path / "out") == 1

    assert_tree(tmp_path / "out", TreeLayout(""))
    assert [
        (record.levelname, record.message) for record in caplog.records
    ] == snapshot(
        [
            ("ERROR", "note.md: out of date: re-run documator to write it"),
            ("INFO", "checked note.md"),
            ("ERROR", "1 file, 0 warnings, 1 error"),
            ("ERROR", "note.md: out of date: re-run documator to write it"),
        ]
    )


def test_check_passes_on_a_tree_a_render_just_produced(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
              sub
                data.csv | a,b\\n1,2\\n
            out
        """),
    )
    assert _render(tmp_path / "in", tmp_path / "out") == 0

    with caplog.at_level(logging.INFO, logger="documator"):
        assert _check(tmp_path / "in", tmp_path / "out") == 0

    assert [
        (record.levelname, record.message) for record in caplog.records
    ] == snapshot(
        [
            ("INFO", "checked note.md"),
            ("INFO", "checked sub/data.csv"),
            ("INFO", "2 files, 0 warnings, 0 errors"),
        ]
    )


def test_check_reports_a_tracked_output_the_run_no_longer_produces(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
              gone.md | stale\\n
            out
        """),
    )
    assert _render(tmp_path / "in", tmp_path / "out") == 0
    (tmp_path / "in" / "gone.md").unlink()

    with caplog.at_level(logging.INFO, logger="documator"):
        assert _check(tmp_path / "in", tmp_path / "out") == 1

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            gone.md | <!-- Generated by documator from gone.md — edit the template, not this file. -->\\nstale\\n
            note.md | <!-- Generated by documator from note.md — edit the template, not this file. -->\\n# Note\\n
        """),
    )
    assert [
        (record.levelname, record.message) for record in caplog.records
    ] == snapshot(
        [
            ("ERROR", "gone.md: no longer produced: re-run documator to prune it"),
            ("INFO", "checked note.md"),
            ("ERROR", "1 file, 0 warnings, 1 error"),
            ("ERROR", "gone.md: no longer produced: re-run documator to prune it"),
        ]
    )


def test_check_reports_an_output_whose_template_changed(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
            out
        """),
    )
    assert _render(tmp_path / "in", tmp_path / "out") == 0
    (tmp_path / "in" / "note.md").write_text("# Renamed\n")

    assert _check(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "note.md").read_text() == snapshot("""\
<!-- Generated by documator from note.md — edit the template, not this file. -->
# Note
""")


def test_check_reports_a_copy_whose_file_mode_changed(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              script.sh | echo hi\\n
            out
        """),
    )
    assert _render(tmp_path / "in", tmp_path / "out") == 0
    (tmp_path / "in" / "script.sh").chmod(0o755)

    assert _check(tmp_path / "in", tmp_path / "out") == 1


def test_go_template_in_a_command_survives_untouched(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | ```\\n!echo '{{.Name}} {{ end }}'\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "note.md").read_text() == snapshot("""\
<!-- Generated by documator from note.md — edit the template, not this file. -->
```
{{.Name}} {{ end }}
```
""")


def test_a_command_inside_a_marked_section_never_runs(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n\\n## _Notes\\n\\n```\\n!touch ran.txt\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "note.md").read_text() == snapshot("""\
<!-- Generated by documator from note.md — edit the template, not this file. -->
# Note
""")
    assert not (tmp_path / "in" / "ran.txt").exists()
