import logging
from pathlib import Path

import pytest
from inline_snapshot import snapshot

from documator.domain import ExitCode, InputDir, OutputDir, TimeoutSeconds
from documator.engine import Adoption, Mode
from documator.render import render
from documator.skills import skills
from documator.tree_layout import TreeLayout, assert_tree, build_tree


def _adopt(input_dir: InputDir, output_dir: OutputDir) -> ExitCode:
    return render(
        input_dir, output_dir, TimeoutSeconds(10.0), Mode.WRITE, Adoption.ADOPT
    )


def _preview(input_dir: InputDir, output_dir: OutputDir) -> ExitCode:
    return render(
        input_dir, output_dir, TimeoutSeconds(10.0), Mode.CHECK, Adoption.ADOPT
    )


def _render(input_dir: InputDir, output_dir: OutputDir) -> ExitCode:
    return render(input_dir, output_dir, TimeoutSeconds(10.0))


def test_adopting_overwrites_a_foreign_file_and_records_it_as_ours(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
            out
              note.md | mine\\n
        """),
    )

    assert _adopt(InputDir(tmp_path / "in"), OutputDir(tmp_path / "out")) == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout(
            "note.md | <!-- Generated by documator from note.md"
            " — edit the template, not this file. -->\\n# Note\\n"
        ),
    )
    assert (tmp_path / "out" / ".documator-manifest.json").read_text() == snapshot("""\
{
  "note.md": "note.md"
}
""")


# Taking ownership is the whole of it: an adopted file is pruned like anything else once
# the template behind it goes away.
def test_an_adopted_file_is_pruned_once_its_template_disappears(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
            out
              note.md | mine\\n
        """),
    )
    assert _adopt(InputDir(tmp_path / "in"), OutputDir(tmp_path / "out")) == 0
    (tmp_path / "in" / "note.md").unlink()

    assert _render(InputDir(tmp_path / "in"), OutputDir(tmp_path / "out")) == 0

    assert_tree(tmp_path / "out", TreeLayout(""))


def test_adopting_leaves_a_foreign_file_no_template_lands_on(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
            out
              mine
                notes.md | mine\\n
        """),
    )

    assert _adopt(InputDir(tmp_path / "in"), OutputDir(tmp_path / "out")) == 0

    assert (tmp_path / "out" / "mine" / "notes.md").read_text() == "mine\n"


def test_adopting_never_reaches_documators_own_bookkeeping(tmp_path: Path) -> None:
    build_tree(tmp_path, TreeLayout("in\nout"))
    (tmp_path / "in" / ".documator-manifest.json").write_text("mine\n")

    assert _adopt(InputDir(tmp_path / "in"), OutputDir(tmp_path / "out")) == 2

    assert (tmp_path / "out" / ".documator-manifest.json").read_text() == snapshot("""\
{}
""")


# Clearing the way for a directory would mean a delete, and adoption buys an overwrite.
def test_adopting_still_refuses_a_file_standing_where_a_directory_belongs(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md
                inner.md | inner\\n
            out
              note.md | mine\\n
        """),
    )

    assert _adopt(InputDir(tmp_path / "in"), OutputDir(tmp_path / "out")) == 2

    assert (tmp_path / "out" / "note.md").read_text() == "mine\n"


def test_adopting_with_nothing_to_adopt_changes_nothing(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
            out
        """),
    )
    assert _render(InputDir(tmp_path / "in"), OutputDir(tmp_path / "out")) == 0

    assert _adopt(InputDir(tmp_path / "in"), OutputDir(tmp_path / "out")) == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout(
            "note.md | <!-- Generated by documator from note.md"
            " — edit the template, not this file. -->\\n# Note\\n"
        ),
    )


def test_adopting_names_every_file_it_takes_over(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              first.md | # First\\n
              second.md | # Second\\n
            out
              first.md | mine\\n
              second.md | also mine\\n
        """),
    )

    with caplog.at_level(logging.INFO, logger="documator"):
        assert _adopt(InputDir(tmp_path / "in"), OutputDir(tmp_path / "out")) == 0

    assert caplog.messages == snapshot(
        [
            "adopted first.md",
            "adopted second.md",
            "rendered first.md",
            "rendered second.md",
            "2 files, 1 warning, 0 errors",
            "adopted 2 files not previously written by documator",
        ]
    )


# The count is the one line a scripted run still sees, because the per-file lines are INFO
# and a takeover destroys files documator did not write.
def test_the_takeover_is_summarised_above_quiet(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
            out
              note.md | mine\\n
        """),
    )

    with caplog.at_level(logging.WARNING, logger="documator"):
        assert _adopt(InputDir(tmp_path / "in"), OutputDir(tmp_path / "out")) == 0

    assert caplog.messages == snapshot(
        [
            "1 file, 1 warning, 0 errors",
            "adopted 1 file not previously written by documator",
        ]
    )


def test_previewing_an_adoption_reports_it_instead_of_refusing_it(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
            out
              note.md | mine\\n
        """),
    )

    with caplog.at_level(logging.WARNING, logger="documator"):
        assert _preview(InputDir(tmp_path / "in"), OutputDir(tmp_path / "out")) == 1

    assert (tmp_path / "out" / "note.md").read_text() == "mine\n"
    assert caplog.messages == snapshot(
        [
            "note.md: would overwrite: not written by documator (--adopt)",
            "0 files, 1 warning, 1 error",
            "would adopt 1 file not previously written by documator",
            "note.md: would overwrite: not written by documator (--adopt)",
        ]
    )


def test_the_refusal_says_how_to_get_past_it(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
            out
              note.md | mine\\n
        """),
    )

    with caplog.at_level(logging.ERROR, logger="documator"):
        assert _render(InputDir(tmp_path / "in"), OutputDir(tmp_path / "out")) == 2

    assert caplog.messages == snapshot(
        [
            "note.md: refusing to overwrite: not written by documator"
            " (pass --adopt to take ownership)",
            "0 files, 0 warnings, 1 error",
            "note.md: refusing to overwrite: not written by documator"
            " (pass --adopt to take ownership)",
        ]
    )


# A manifest that fails to parse disowns everything, after which documator refuses its own
# output forever. Adoption is the way back.
def test_a_run_disowned_by_a_corrupt_manifest_is_reclaimed_by_adopting(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
            out
        """),
    )
    assert _render(InputDir(tmp_path / "in"), OutputDir(tmp_path / "out")) == 0
    (tmp_path / "out" / ".documator-manifest.json").write_text("not json at all\n")
    assert _render(InputDir(tmp_path / "in"), OutputDir(tmp_path / "out")) == 2

    assert _adopt(InputDir(tmp_path / "in"), OutputDir(tmp_path / "out")) == 0

    assert (tmp_path / "out" / ".documator-manifest.json").read_text() == snapshot("""\
{
  "note.md": "note.md"
}
""")


def test_a_manifest_that_cannot_be_read_says_so(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
            out
              .documator-manifest.json | not json at all\\n
        """),
    )

    with caplog.at_level(logging.WARNING, logger="documator"):
        assert _render(InputDir(tmp_path / "in"), OutputDir(tmp_path / "out")) == 0

    assert caplog.messages == snapshot(
        [
            ".documator-manifest.json is unreadable: nothing counts as documator's own"
            " until a run reclaims it with --adopt"
        ]
    )


def test_skills_adopts_a_foreign_file_standing_where_a_skill_lands(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              @plan.md | # Plan\\n
            out
              plan
                SKILL.md | mine\\n
        """),
    )

    assert (
        skills(
            InputDir(tmp_path / "in"),
            OutputDir(tmp_path / "out"),
            TimeoutSeconds(10.0),
            Mode.WRITE,
            Adoption.ADOPT,
        )
        == 0
    )

    assert (tmp_path / "out" / "plan" / "SKILL.md").read_text() == snapshot("""\
---
name: plan
description: plan
---
<!-- Generated by documator from @plan.md — edit the template, not this file. -->
# Plan
""")


# A claims file is rewritten by every run, so an unreadable one costs nothing: pointing
# at --adopt there would send the reader after a problem they do not have.
def test_an_unreadable_claims_file_says_nothing_about_adopting(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
            out
              .documator-claims.json | not json at all\\n
        """),
    )

    with caplog.at_level(logging.WARNING, logger="documator"):
        assert _render(InputDir(tmp_path / "in"), OutputDir(tmp_path / "out")) == 0

    assert caplog.messages == []
