import logging
from pathlib import Path

import pytest
from inline_snapshot import snapshot
from pydantic import ValidationError

from documator.domain import InputDir, OutputDir, TimeoutSeconds
from documator.render import render
from documator.transclusion import NotePath
from documator.tree_layout import TreeLayout, assert_tree, build_tree


def _render(input_dir: Path, output_dir: Path) -> int:
    return render(InputDir(input_dir), OutputDir(output_dir), TimeoutSeconds(10.0))


def test_inlines_the_full_contents_of_a_matching_note(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | before\\n\\n![[Shared]]\\n\\nafter\\n
              Shared.md | # Shared\\n\\nbody\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
before

# Shared

body


after
""")


def test_frontmatter_of_a_transcluded_note_is_left_behind(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | before\\n\\n![[Shared]]\\n\\nafter\\n
              Shared.md | ---\\ndescription: shared\\n---\\nbody\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
before

body


after
""")


def test_frontmatter_below_the_first_line_of_a_transcluded_note_is_kept(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared]]\\n
              Shared.md | body\\n\\n---\\ndescription: not frontmatter\\n---\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
body

---
description: not frontmatter
---

""")


def test_matches_a_note_case_insensitively(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[shared note]]\\n
              Shared Note.md | body\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
body

""")


def test_matches_a_note_named_with_its_extension(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared.md]]\\n
              Shared.md | body\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
body

""")


def test_matches_a_note_anywhere_in_the_vault(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              deep
                index.md | ![[Shared]]\\n
              other
                Shared.md | body\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "deep" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from deep/index.md — edit the template, not this file. -->
body

""")


def test_path_qualified_reference_disambiguates_a_collision(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[left/Shared]]\\n
              left
                Shared.md | from left\\n
              right
                Shared.md | from right\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
from left

""")


def test_transcluded_note_executes_its_own_blocks(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared]]\\n
              Shared.md | ```\\n!echo live\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
```
live
```

""")


def test_transcluded_block_runs_beside_the_note_it_came_from(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared]]\\n
              sub
                Shared.md | ```\\n!cat sibling.txt\\n```\\n
                sibling.txt | neighbour\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
```
neighbour
```

""")


def test_nested_transclusion_is_inlined(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | top\\n\\n![[Middle]]\\n
              Middle.md | middle\\n\\n![[Leaf]]\\n
              Leaf.md | leaf\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
top

middle

leaf


""")


def test_the_same_note_may_be_transcluded_twice(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared]]![[Shared]]\\n
              Shared.md | body\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
body
body

""")


def test_transclusion_inside_a_fence_is_left_alone(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ```\\nwrite ![[Shared]] to embed\\n```\\n
              Shared.md | body\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
```
write ![[Shared]] to embed
```
""")


def test_transclusion_is_re_resolved_on_every_render(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared]]\\n
              Shared.md | first\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0
    (tmp_path / "in" / "Shared.md").write_text("second\n")
    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
second

""")


def test_no_match_marks_the_failure_in_place_and_is_operational(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | before ![[Missing]] after\\n
            out
        """),
    )

    with caplog.at_level(logging.ERROR, logger="documator"):
        assert _render(tmp_path / "in", tmp_path / "out") == 2

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
before [documator: no note matches transclusion "Missing"] after
""")
    assert "index.md" in caplog.text


def test_ambiguous_reference_marks_the_candidates_in_place(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared]]\\n
              left
                Shared.md | from left\\n
              right
                Shared.md | from right\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 2

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
[documator: transclusion "Shared" matches left/Shared.md, right/Shared.md]
""")


def test_a_fragment_selects_only_that_section(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared#Usage]]\\n
              Shared.md | # Shared\\n\\n## Install\\n\\nrun it\\n\\n## Usage\\n\\nuse it\\n\\n## Notes\\n\\nnope\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
## Usage

use it

""")


def test_a_heading_path_selects_a_nested_section(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared#Server#Usage]]\\n
              Shared.md | ## Client\\n\\n### Usage\\n\\nclient side\\n\\n## Server\\n\\n### Usage\\n\\nserver side\\n\\n### Notes\\n\\nnope\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
### Usage

server side

""")


def test_a_section_does_not_see_variables_declared_above_it(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared#Usage]]\\n
              Shared.md | ```\\n!var greeting = echo hi\\n```\\n\\n## Usage\\n\\n```\\n!{{greeting}}\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
## Usage

```
!{{greeting}}
```

[documator: undefined variable greeting]

""")


def test_an_alias_does_not_change_which_section_is_selected(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared#Usage|How to use it]]\\n
              Shared.md | ## Usage\\n\\nuse it\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
## Usage

use it

""")


def test_a_trailing_hash_names_no_section(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared#]]\\n
              Shared.md | ## Usage\\n\\nuse it\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 2

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
[documator: transclusion "Shared#" names an empty section]
""")


def test_an_empty_segment_inside_a_path_names_no_section(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared##Usage]]\\n
              Shared.md | ## Usage\\n\\nuse it\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 2

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
[documator: transclusion "Shared##Usage" names an empty section]
""")


def test_a_block_reference_is_unsupported(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared#^abc123]]\\n
              Shared.md | ## Usage\\n\\nuse it\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 2

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
[documator: transclusion "Shared#^abc123" names a block reference, which is unsupported]
""")


def test_a_missing_section_names_what_the_note_does_have(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared#Setup]]\\n
              Shared.md | ## Usage\\n\\nuse it\\n\\n## Install\\n\\nget it\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 2

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
[documator: no section "Setup" in Shared.md; it has Usage, Install]
""")


def test_a_missing_nested_section_names_the_path_it_looked_under(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared#Server#Setup]]\\n
              Shared.md | ## Server\\n\\n### Install\\n\\nget it\\n\\n## Client\\n\\n### Setup\\n\\nnope\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 2

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
[documator: no section "Setup" under Shared.md#Server; it has Install]
""")


def test_two_headings_with_the_same_name_are_ambiguous(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared#Usage]]\\n
              Shared.md | ## Usage\\n\\nfirst\\n\\n## Usage\\n\\nsecond\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 2

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
[documator: section Shared.md#Usage matches more than one heading]
""")


def test_a_sibling_section_of_the_same_note_is_not_a_cycle(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared#One]]\\n
              Shared.md | ## One\\n\\n![[Shared#Two]]\\n\\n## Two\\n\\nsecond\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
## One

## Two

second


""")


def test_a_section_transcluding_itself_is_a_cycle(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared#One]]\\n
              Shared.md | ## One\\n\\n![[Shared#One]]\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 2

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
## One

[documator: transclusion cycle: index.md -> Shared.md#One -> Shared.md#One]

""")


def test_a_cycle_is_marked_in_place_rather_than_hanging(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Middle]]\\n
              Middle.md | ![[index]]\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 2

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
[documator: transclusion cycle: index.md -> Middle.md -> index.md]

""")


def test_a_note_transcluding_itself_is_a_cycle(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[index]]\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 2

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
[documator: transclusion cycle: index.md -> index.md]
""")


def test_an_operational_failure_outranks_a_block_failure(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              a.md | ```\\n!exit 3\\n```\\n
              b.md | ![[Missing]]\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 2


def test_a_failing_block_in_a_transcluded_note_fails_the_run(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared]]\\n
              Shared.md | ```\\n!exit 3\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
```
[documator: exit 3]
```

""")


def test_a_transcluded_note_is_still_rendered_on_its_own(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared]]\\n
              Shared.md | ```\\n!echo live\\n```\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            index.md | <!-- Generated by documator from index.md — edit the template, not this file. -->\\n```\\nlive\\n```\\n\\n
            Shared.md | <!-- Generated by documator from Shared.md — edit the template, not this file. -->\\n```\\nlive\\n```\\n
        """),
    )


def test_a_non_markdown_embed_is_left_untouched(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[diagram.png]]\\n
              diagram.png | not really a png\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
![[diagram.png]]
""")


def test_a_fragment_on_a_non_markdown_embed_is_left_untouched(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[report.pdf#page=2]]\\n
              report.pdf | not really a pdf\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
![[report.pdf#page=2]]
""")


def test_a_block_reference_on_a_non_markdown_embed_is_left_untouched(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[report.pdf#^abc123]]\\n
              report.pdf | not really a pdf\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
![[report.pdf#^abc123]]
""")


def test_a_section_naming_itself_with_other_casing_is_a_cycle(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Shared#Usage]]\\n
              Shared.md | ## Usage\\n\\n![[Shared#usage]]\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 2

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
## Usage

[documator: transclusion cycle: index.md -> Shared.md#Usage -> Shared.md#usage]

""")


def test_an_unmatched_markdown_reference_is_still_an_error(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Missing.md]]\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 2

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
[documator: no note matches transclusion "Missing.md"]
""")


def test_a_dotted_note_name_still_transcludes(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Release 1.0 notes]]\\n
              Release 1.0 notes.md | shipped\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
shipped

""")


def test_an_embed_of_a_file_the_vault_lacks_is_an_error(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              index.md | ![[Release 1.0 notes]]\\n
            out
        """),
    )

    assert _render(tmp_path / "in", tmp_path / "out") == 2

    assert (tmp_path / "out" / "index.md").read_text() == snapshot("""\
<!-- Generated by documator from index.md — edit the template, not this file. -->
[documator: no note matches transclusion "Release 1.0 notes"]
""")


def test_a_vault_path_must_be_relative_to_the_vault(tmp_path: Path) -> None:
    with pytest.raises(ValidationError):
        NotePath(tmp_path / "note.md")
