import os
import pty
import re
import signal
import subprocess
import sys
import time
from collections.abc import Callable
from pathlib import Path

from inline_snapshot import snapshot

from documator.cli import main
from documator.tree_layout import TreeLayout, assert_tree, build_tree

WATCH_DEADLINE_SECONDS = 15.0


def _wait_for(
    done: Callable[[], bool], nudge: Callable[[], None] = lambda: None
) -> None:
    deadline = time.monotonic() + WATCH_DEADLINE_SECONDS
    while time.monotonic() < deadline:
        nudge()
        if done():
            return
        time.sleep(0.05)
    raise AssertionError("the watching CLI never reached the expected state")


def test_render_with_valid_args_exits_zero(tmp_path: Path) -> None:
    build_tree(tmp_path, TreeLayout("in\nout"))

    assert main(["render", str(tmp_path / "in"), str(tmp_path / "out")]) == 0


def test_render_with_missing_input_dir_exits_two(tmp_path: Path) -> None:
    build_tree(tmp_path, TreeLayout("out"))

    assert main(["render", str(tmp_path / "nope"), str(tmp_path / "out")]) == 2


def test_render_with_missing_output_dir_exits_two(tmp_path: Path) -> None:
    build_tree(tmp_path, TreeLayout("in"))

    assert main(["render", str(tmp_path / "in"), str(tmp_path / "nope")]) == 2


def test_render_mirrors_the_input_tree(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
            out
        """),
    )

    assert main(["render", str(tmp_path / "in"), str(tmp_path / "out")]) == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout(
            "note.md | <!-- Generated by documator from note.md"
            " — edit the template, not this file. -->\\n# Note\\n"
        ),
    )


def test_render_with_a_failing_block_exits_one(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | ```\\n!exit 3\\n```\\n
            out
        """),
    )

    assert main(["render", str(tmp_path / "in"), str(tmp_path / "out")]) == 1


def test_timeout_flag_bounds_a_block(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | ```\\n!sleep 5\\n```\\n
            out
        """),
    )

    args = ["render", str(tmp_path / "in"), str(tmp_path / "out"), "--timeout", "0.3"]
    assert main(args) == 1

    assert_tree(
        tmp_path / "out",
        TreeLayout(
            "note.md | <!-- Generated by documator from note.md"
            " — edit the template, not this file. -->\\n"
            "```\\n[documator: timed out after 0.3s]\\n```\\n"
        ),
    )


def test_default_timeout_lets_a_short_command_finish(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | ```\\n!sleep 0.5; echo done\\n```\\n
            out
        """),
    )

    assert main(["render", str(tmp_path / "in"), str(tmp_path / "out")]) == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout(
            "note.md | <!-- Generated by documator from note.md"
            " — edit the template, not this file. -->\\n```\\ndone\\n```\\n"
        ),
    )


def test_render_into_nested_output_exits_two(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              out
        """),
    )

    assert main(["render", str(tmp_path / "in"), str(tmp_path / "in" / "out")]) == 2


def test_render_accepts_an_explicit_timeout(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | # Note\\n
            out
        """),
    )

    args = ["render", str(tmp_path / "in"), str(tmp_path / "out"), "--timeout", "2.5"]
    assert main(args) == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout(
            "note.md | <!-- Generated by documator from note.md"
            " — edit the template, not this file. -->\\n# Note\\n"
        ),
    )


def test_non_numeric_timeout_exits_two(tmp_path: Path) -> None:
    build_tree(tmp_path, TreeLayout("in\nout"))

    args = ["render", str(tmp_path / "in"), str(tmp_path / "out"), "--timeout", "soon"]
    assert main(args) == 2


def test_non_positive_timeout_exits_two(tmp_path: Path) -> None:
    build_tree(tmp_path, TreeLayout("in\nout"))

    args = ["render", str(tmp_path / "in"), str(tmp_path / "out"), "--timeout", "0"]
    assert main(args) == 2


def test_unknown_flag_exits_two(tmp_path: Path) -> None:
    build_tree(tmp_path, TreeLayout("in\nout"))

    args = ["render", str(tmp_path / "in"), str(tmp_path / "out"), "--parallel"]
    assert main(args) == 2


def test_skills_flattens_a_nested_template_tree(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              a
                foo.md | # Foo\\n
            out
        """),
    )

    assert main(["skills", str(tmp_path / "in"), str(tmp_path / "out")]) == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            foo
              SKILL.md | ---\\nname: foo\\ndescription: foo\\n---\\n<!-- Generated by documator from a/foo.md — edit the template, not this file. -->\\n# Foo\\n
        """),
    )


def test_skills_with_a_failing_block_exits_one(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | ```\\n!exit 3\\n```\\n
            out
        """),
    )

    assert main(["skills", str(tmp_path / "in"), str(tmp_path / "out")]) == 1


def test_skills_with_missing_input_dir_exits_two(tmp_path: Path) -> None:
    build_tree(tmp_path, TreeLayout("out"))

    assert main(["skills", str(tmp_path / "nope"), str(tmp_path / "out")]) == 2


def test_skills_timeout_flag_bounds_a_block(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | ```\\n!sleep 5\\n```\\n
            out
        """),
    )

    args = ["skills", str(tmp_path / "in"), str(tmp_path / "out"), "--timeout", "0.3"]
    assert main(args) == 1

    assert (tmp_path / "out" / "foo" / "SKILL.md").read_text() == snapshot("""\
---
name: foo
description: foo
---
<!-- Generated by documator from foo.md — edit the template, not this file. -->
```
[documator: timed out after 0.3s]
```
""")


def test_log_lines_carry_a_timestamp_and_level(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | hello\\n
            out
        """),
    )

    # The format only applies to the real handler, so drive the CLI out-of-process.
    logged = subprocess.run(
        [
            sys.executable,
            "-m",
            "documator",
            "render",
            str(tmp_path / "in"),
            str(tmp_path / "out"),
        ],
        capture_output=True,
        text=True,
        check=True,
    ).stderr

    assert re.fullmatch(
        r"\d{2}:\d{2}:\d{2} INFO    rendered note\.md\n"
        r"\d{2}:\d{2}:\d{2} INFO    1 file, 0 warnings, 0 errors\n",
        logged,
    )


def test_log_lines_are_coloured_on_a_terminal(tmp_path: Path) -> None:
    build_tree(tmp_path, TreeLayout("in\n  note.md | hello\\n\nout"))

    # A pty is the only thing colour keys off, so it is the only way to observe it.
    reader, terminal = pty.openpty()
    subprocess.run(
        [
            sys.executable,
            "-m",
            "documator",
            "render",
            str(tmp_path / "in"),
            str(tmp_path / "out"),
        ],
        stdout=subprocess.DEVNULL,
        stderr=terminal,
        check=True,
        # The task runner sets NO_COLOR, which is honoured; this test is about the
        # terminal, so it asks the question with that answer removed.
        env={key: value for key, value in os.environ.items() if key != "NO_COLOR"},
    )
    # Read before the last writer closes: BSD ptys drop whatever is still buffered.
    logged = os.read(reader, 4096).decode()
    os.close(terminal)
    os.close(reader)

    assert "\x1b[" in logged


def _stderr_of(arguments: list[str]) -> str:
    return subprocess.run(
        [sys.executable, "-m", "documator", *arguments],
        capture_output=True,
        text=True,
    ).stderr


def test_quiet_leaves_a_clean_run_silent(tmp_path: Path) -> None:
    build_tree(tmp_path, TreeLayout("in\n  note.md | hello\\n\nout"))

    logged = _stderr_of(
        ["--quiet", "render", str(tmp_path / "in"), str(tmp_path / "out")]
    )

    assert logged == ""


def test_quiet_keeps_warnings_errors_and_the_summary(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              Foo.md | # Foo\\n
              helper.py | print("hi")\\n
            out
        """),
    )

    logged = _stderr_of(
        ["--quiet", "skills", str(tmp_path / "in"), str(tmp_path / "out")]
    )

    assert re.sub(r"\d{2}:\d{2}:\d{2} ", "", logged) == snapshot("""\
WARNING helper.py: ignored, move it into a SKILL.md folder to bundle it
ERROR   Foo.md: "Foo" is not a valid skill name
ERROR   1 file, 1 warning, 1 error
WARNING helper.py: ignored, move it into a SKILL.md folder to bundle it
ERROR   Foo.md: "Foo" is not a valid skill name
""")


def test_a_failing_block_logs_at_error_level(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | ```\\n!exit 3\\n```\\n
            out
        """),
    )

    logged = subprocess.run(
        [
            sys.executable,
            "-m",
            "documator",
            "render",
            str(tmp_path / "in"),
            str(tmp_path / "out"),
        ],
        capture_output=True,
        text=True,
    ).stderr

    assert re.search(
        r"^\d{2}:\d{2}:\d{2} ERROR   note\.md: exit 3: exit 3$", logged, re.MULTILINE
    )


def test_watch_flag_keeps_rendering_after_the_first_pass(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              note.md | original\\n
            out
        """),
    )
    rendered = tmp_path / "out" / "note.md"

    def edit() -> None:
        (tmp_path / "in" / "note.md").write_text("edited\n")

    # --watch never returns, so drive the real CLI out-of-process and kill it.
    process = subprocess.Popen(
        [
            sys.executable,
            "-m",
            "documator",
            "render",
            str(tmp_path / "in"),
            str(tmp_path / "out"),
            "--watch",
        ]
    )

    try:
        # The first pass runs before the watcher arms, so wait it out before editing;
        # only a re-render can turn the output into "edited" afterwards.
        _wait_for(
            lambda: (
                rendered.is_file()
                and rendered.read_text()
                == "<!-- Generated by documator from note.md — edit the template, not this file. -->\n"
                "original\n"
            )
        )
        _wait_for(
            lambda: (
                rendered.read_text()
                == "<!-- Generated by documator from note.md — edit the template, not this file. -->\n"
                "edited\n"
            ),
            edit,
        )
    finally:
        process.terminate()
        process.wait(timeout=WATCH_DEADLINE_SECONDS)


def test_skills_watch_flag_recompiles_and_interrupting_exits_zero(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | # Foo\\n
            out
        """),
    )
    compiled = tmp_path / "out" / "bar" / "SKILL.md"

    def add() -> None:
        (tmp_path / "in" / "bar.md").write_text("# Bar\n")

    process = subprocess.Popen(
        [
            sys.executable,
            "-m",
            "documator",
            "skills",
            str(tmp_path / "in"),
            str(tmp_path / "out"),
            "--watch",
        ]
    )

    try:
        _wait_for(lambda: (tmp_path / "out" / "foo" / "SKILL.md").is_file())
        _wait_for(lambda: compiled.is_file(), add)
    finally:
        # Ctrl-C is how a session ends, and ending one is not a failure.
        process.send_signal(signal.SIGINT)

    assert process.wait(timeout=WATCH_DEADLINE_SECONDS) == 0
