import logging
from pathlib import Path

import pytest
from inline_snapshot import snapshot

from documator.domain import InputDir, OutputDir, TimeoutSeconds
from documator.engine import ConflictReason
from documator.skills import skills
from documator.tree_layout import TreeLayout, assert_tree, build_tree


def _skills(input_dir: Path, output_dir: Path) -> int:
    return skills(InputDir(input_dir), OutputDir(output_dir), TimeoutSeconds(10.0))


def _emitted(output_dir: Path) -> list[str]:
    return sorted(str(path.relative_to(output_dir)) for path in output_dir.rglob("*"))


def test_nesting_never_appears_in_the_name_or_the_output_path(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              a
                b
                  foo.md | # Foo\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            foo
              SKILL.md | ---\\nname: foo\\ndescription: foo\\n---\\n<!-- Generated by documator from a/b/foo.md — edit the template, not this file. -->\\n# Foo\\n
        """),
    )


def test_command_blocks_execute_beside_their_own_template(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              sub
                foo.md | ```\\n!cat sibling.txt\\n```\\n
                sibling.txt | neighbour\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "foo" / "SKILL.md").read_text() == snapshot("""\
---
name: foo
description: foo
---
<!-- Generated by documator from sub/foo.md — edit the template, not this file. -->
```
neighbour
```
""")


def test_transclusions_inline(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | before ![[shared]] after\\n
              parts
                shared.md | inlined
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "foo" / "SKILL.md").read_text() == snapshot("""\
---
name: foo
description: foo
---
<!-- Generated by documator from foo.md — edit the template, not this file. -->
before inlined after
""")


def test_declared_description_overrides_the_derived_one(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | ---\\ndescription: does a thing\\nmodel: opus\\n---\\n\\n# Foo\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "foo" / "SKILL.md").read_text() == snapshot("""\
---
name: foo
description: does a thing
model: opus
---
<!-- Generated by documator from foo.md — edit the template, not this file. -->

# Foo
""")


def test_frontmatter_cannot_come_from_a_command_block(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | ```\\n!cat injected.txt\\n```\\n
              injected.txt | ---\\ndescription: injected\\n---\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "foo" / "SKILL.md").read_text() == snapshot("""\
---
name: foo
description: foo
---
<!-- Generated by documator from foo.md — edit the template, not this file. -->
```
---
description: injected
---
```
""")


def test_frontmatter_is_not_inherited_from_a_transclusion(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | ![[shared]]
              shared.md | ---\\ndescription: inherited\\n---\\nshared body\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "foo" / "SKILL.md").read_text() == snapshot("""\
---
name: foo
description: foo
---
<!-- Generated by documator from foo.md — edit the template, not this file. -->
shared body
""")


def test_a_tracked_output_this_run_no_longer_produces_is_pruned(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | # Foo\\n
              gone.md | # Gone\\n
            out
        """),
    )
    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    (tmp_path / "in" / "gone.md").unlink()

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            foo
              SKILL.md | ---\\nname: foo\\ndescription: foo\\n---\\n<!-- Generated by documator from foo.md — edit the template, not this file. -->\\n# Foo\\n
        """),
    )


def test_a_failing_block_still_compiles_and_prunes_the_rest(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              a.md | ```\\n!echo partial; exit 3\\n```\\n
              b.md | ```\\n!echo second\\n```\\n
              gone.md | # Gone\\n
            out
        """),
    )
    assert _skills(tmp_path / "in", tmp_path / "out") == 1

    (tmp_path / "in" / "gone.md").unlink()

    assert _skills(tmp_path / "in", tmp_path / "out") == 1

    assert not (tmp_path / "out" / "gone").exists()
    assert (tmp_path / "out" / "a" / "SKILL.md").read_text() == snapshot("""\
---
name: a
description: a
---
<!-- Generated by documator from a.md — edit the template, not this file. -->
```
partial
[documator: exit 3]
```
""")
    assert (tmp_path / "out" / "b" / "SKILL.md").read_text() == snapshot("""\
---
name: b
description: b
---
<!-- Generated by documator from b.md — edit the template, not this file. -->
```
second
```
""")


def test_a_folder_holding_skill_md_compiles_under_its_folder_name(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              guides
                plan
                  SKILL.md | # Body\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            plan
              SKILL.md | ---\\nname: plan\\ndescription: plan\\n---\\n<!-- Generated by documator from guides/plan/SKILL.md — edit the template, not this file. -->\\n# Body\\n
        """),
    )


def test_the_whole_subtree_is_bundled_with_its_structure_preserved(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              guides
                plan
                  SKILL.md | # Body\\n
                  references
                    spec.pdf | %PDF-fake\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            plan
              SKILL.md | ---\\nname: plan\\ndescription: plan\\n---\\n<!-- Generated by documator from guides/plan/SKILL.md — edit the template, not this file. -->\\n# Body\\n
              references
                spec.pdf | %PDF-fake\\n
        """),
    )


def test_an_inert_or_invisible_path_inside_a_skill_folder_is_not_bundled(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo
                SKILL.md | # Foo\\n
                _draft.md | # Draft\\n
                .cache
                  junk.txt | junk\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            foo
              SKILL.md | ---\\nname: foo\\ndescription: foo\\n---\\n<!-- Generated by documator from foo/SKILL.md — edit the template, not this file. -->\\n# Foo\\n
        """),
    )


def test_an_undecodable_bundled_file_survives_byte_for_byte(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo
                SKILL.md | # Foo\\n
            out
        """),
    )
    (tmp_path / "in" / "foo" / "logo.png").write_bytes(b"\x89PNG\r\n\x1a\n\xff\xfe\x00")

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "foo" / "logo.png").read_bytes() == snapshot(
        b"\x89PNG\r\n\x1a\n\xff\xfe\x00"
    )


# On a case-insensitive filesystem a lowercase manifest must not be mistaken for
# SKILL.md, or the folder skill would be bundled over its own output.
def test_a_lowercase_skill_md_does_not_make_a_skill_folder(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo
                skill.md | # Lower\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            skill
              SKILL.md | ---\\nname: skill\\ndescription: skill\\n---\\n<!-- Generated by documator from foo/skill.md — edit the template, not this file. -->\\n# Lower\\n
        """),
    )


def test_a_bundled_markdown_file_renders_without_generated_frontmatter(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo
                SKILL.md | # Foo\\n
                notes.md | ---\\ndescription: mine\\n---\\n```\\n!echo bundled\\n```\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "foo" / "notes.md").read_text() == snapshot("""\
---
description: mine
---
<!-- Generated by documator from foo/notes.md — edit the template, not this file. -->
```
bundled
```
""")


def test_a_deeper_skill_md_is_bundled_rather_than_producing_a_second_skill(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              outer
                SKILL.md | # Outer\\n
                example
                  SKILL.md | # Example\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            outer
              SKILL.md | ---\\nname: outer\\ndescription: outer\\n---\\n<!-- Generated by documator from outer/SKILL.md — edit the template, not this file. -->\\n# Outer\\n
              example
                SKILL.md | <!-- Generated by documator from outer/example/SKILL.md — edit the template, not this file. -->\\n# Example\\n
        """),
    )


def test_a_bare_markdown_file_inside_a_skill_folder_is_not_its_own_skill(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              outer
                SKILL.md | # Outer\\n
                helper.md | # Helper\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert not (tmp_path / "out" / "helper").exists()


def test_a_folder_without_skill_md_produces_nothing(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              organisational
                notes.txt | loose\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(tmp_path / "out", TreeLayout(""))


def test_logs_each_bundled_file(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              outer
                SKILL.md | # Outer\\n
                example
                  SKILL.md | # Example\\n
            out
        """),
    )

    with caplog.at_level(logging.INFO, logger="documator"):
        assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert "bundled outer/example/SKILL.md into outer/example/SKILL.md" in caplog.text


def test_non_markdown_files_are_not_skills(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              notes.txt | not a skill\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(tmp_path / "out", TreeLayout(""))


def test_dot_prefixed_paths_are_invisible(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | # Foo\\n
              .hidden.md | # Hidden\\n
              .obsidian
                workspace.md | # Workspace\\n
                app.json | {}\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            foo
              SKILL.md | ---\\nname: foo\\ndescription: foo\\n---\\n<!-- Generated by documator from foo.md — edit the template, not this file. -->\\n# Foo\\n
        """),
    )


def test_an_invisible_note_is_not_a_transclusion_target(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | ![[Secret]]
              .hidden
                Secret.md | secret\\n
            out
        """),
    )

    with caplog.at_level(logging.ERROR, logger="documator"):
        assert _skills(tmp_path / "in", tmp_path / "out") == 2

    assert caplog.messages == snapshot(
        [
            'foo.md: no note matches transclusion "Secret"',
            "1 file, 0 warnings, 1 error",
            'foo.md: no note matches transclusion "Secret"',
        ]
    )


def test_an_invisible_attachment_embed_still_passes_through(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | ![[diagram.png]]\\n
              .assets
                diagram.png | binary\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "foo" / "SKILL.md").read_text() == snapshot("""\
---
name: foo
description: foo
---
<!-- Generated by documator from foo.md — edit the template, not this file. -->
![[diagram.png]]
""")


def test_underscore_prefixed_paths_emit_nothing_but_still_transclude(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | ![[Partial]]
              _draft.md | # Draft\\n
              _parts
                Partial.md | inlined\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            foo
              SKILL.md | ---\\nname: foo\\ndescription: foo\\n---\\n<!-- Generated by documator from foo.md — edit the template, not this file. -->\\ninlined\\n
        """),
    )


def test_an_inert_segment_anywhere_on_the_path_produces_no_skill(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              a
                _shared
                  b
                    foo.md | # Foo\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(tmp_path / "out", TreeLayout(""))


def test_an_ignored_loose_file_is_logged_at_warning(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | # Foo\\n
              helper.py | print("hi")\\n
            out
        """),
    )

    with caplog.at_level(logging.INFO, logger="documator"):
        assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert [
        (record.levelname, record.message) for record in caplog.records
    ] == snapshot(
        [
            (
                "WARNING",
                "helper.py: ignored, move it into a SKILL.md folder to bundle it",
            ),
            ("INFO", "compiled foo.md into foo/SKILL.md"),
            ("WARNING", "1 file, 1 warning, 0 errors"),
            (
                "WARNING",
                "helper.py: ignored, move it into a SKILL.md folder to bundle it",
            ),
        ]
    )


def test_an_ignored_inert_path_is_logged_at_info(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              .DS_Store | junk\\n
              _notes
                todo.txt | later\\n
            out
        """),
    )

    with caplog.at_level(logging.INFO, logger="documator"):
        assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert [
        (record.levelname, record.message) for record in caplog.records
    ] == snapshot(
        [
            ("INFO", "ignored .DS_Store"),
            ("INFO", "ignored _notes/todo.txt"),
            ("INFO", "0 files, 0 warnings, 0 errors"),
        ]
    )


def test_the_summary_orders_warnings_before_errors(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              Foo.md | # Foo\\n
              good.md | # Good\\n
              helper.py | print("hi")\\n
            out
        """),
    )

    with caplog.at_level(logging.INFO, logger="documator"):
        assert _skills(tmp_path / "in", tmp_path / "out") == 1

    assert [
        (record.levelname, record.message) for record in caplog.records
    ] == snapshot(
        [
            (
                "WARNING",
                "helper.py: ignored, move it into a SKILL.md folder to bundle it",
            ),
            ("ERROR", 'Foo.md: "Foo" is not a valid skill name'),
            ("INFO", "compiled good.md into good/SKILL.md"),
            ("ERROR", "2 files, 1 warning, 1 error"),
            (
                "WARNING",
                "helper.py: ignored, move it into a SKILL.md folder to bundle it",
            ),
            ("ERROR", 'Foo.md: "Foo" is not a valid skill name'),
        ]
    )


def test_unresolvable_transclusion_is_an_operational_error(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | ![[Missing]]
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 2


def test_identical_input_and_output_leaves_the_tree_untouched(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | # Foo\\n
        """),
    )

    with caplog.at_level(logging.ERROR, logger="documator"):
        assert _skills(tmp_path / "in", tmp_path / "in") == 2

    assert ConflictReason.IDENTICAL in caplog.text
    assert_tree(tmp_path / "in", TreeLayout("foo.md | # Foo\\n"))


def test_an_invalid_name_skips_only_its_own_skill(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              Foo.md | # Foo\\n
              bar.md | # Bar\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 1

    assert _emitted(tmp_path / "out") == snapshot(
        [".documator-manifest.json", "bar", "bar/SKILL.md", "documator-errors.md"]
    )
    assert (tmp_path / "out" / "bar" / "SKILL.md").read_text() == snapshot("""\
---
name: bar
description: bar
---
<!-- Generated by documator from bar.md — edit the template, not this file. -->
# Bar
""")


def test_a_previously_compiled_copy_of_a_failing_skill_is_pruned(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | ---\\ndescription: real\\n---\\n# Foo\\n
            out
        """),
    )
    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    (tmp_path / "in" / "foo.md").write_text("---\ndescription: real\n---\n\n")

    assert _skills(tmp_path / "in", tmp_path / "out") == 1

    assert not (tmp_path / "out" / "foo").exists()


def test_a_collision_emits_neither_side_and_names_both_paths(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              a
                foo.md | # From a\\n
              b
                foo
                  SKILL.md | # From b\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "documator-errors.md").read_text() == snapshot("""\
# documator errors

- the name "foo" is claimed by a/foo.md and b/foo/SKILL.md
""")
    assert not (tmp_path / "out" / "foo").exists()


def test_a_collision_is_decided_before_any_command_block_runs(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              a
                foo.md | ```\\n!touch ../../ran\\n```\\n
              b
                foo.md | # From b\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 1

    assert not (tmp_path / "ran").exists()


def test_an_invalid_name_is_decided_before_any_command_block_runs(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              Foo.md | ```\\n!touch ../ran\\n```\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 1

    assert not (tmp_path / "ran").exists()


def test_the_errors_file_is_pruned_by_a_later_clean_run(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              Foo.md | # Foo\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 1
    (tmp_path / "in" / "Foo.md").rename(tmp_path / "in" / "foo.md")

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert_tree(
        tmp_path / "out",
        TreeLayout("""
            foo
              SKILL.md | ---\\nname: foo\\ndescription: foo\\n---\\n<!-- Generated by documator from foo.md — edit the template, not this file. -->\\n# Foo\\n
        """),
    )


def test_an_empty_skill_md_fails_even_when_the_folder_bundles_files(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo
                SKILL.md | \\n
                references
                  spec.md | # Spec\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 1

    assert _emitted(tmp_path / "out") == snapshot(
        [".documator-manifest.json", "documator-errors.md"]
    )


def test_a_body_that_renders_to_nothing_is_not_a_structural_failure(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | ```\\n!true\\n```\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert (tmp_path / "out" / "foo" / "SKILL.md").read_text() == snapshot("""\
---
name: foo
description: foo
---
<!-- Generated by documator from foo.md — edit the template, not this file. -->
```
```
""")


def test_a_declared_name_fails_even_when_it_matches_the_derived_one(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | ---\\nname: foo\\n---\\n# Foo\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "documator-errors.md").read_text() == snapshot("""\
# documator errors

- foo.md (foo): the template declares name, which the compiler sets
""")


def test_an_explicitly_empty_description_fails(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              foo.md | ---\\ndescription:\\n---\\n# Foo\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "documator-errors.md").read_text() == snapshot("""\
# documator errors

- foo.md (foo): the template declares an empty description
""")


def test_an_undecodable_template_is_reported_rather_than_crashing(
    tmp_path: Path,
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              bar.md | # Bar\\n
            out
        """),
    )
    (tmp_path / "in" / "foo.md").write_bytes(b"# \xff\xfe\n")

    assert _skills(tmp_path / "in", tmp_path / "out") == 1

    reported = (tmp_path / "out" / "documator-errors.md").read_text()

    assert reported.startswith(
        "# documator errors\n\n- foo.md (foo): the template cannot be read: "
    )
    assert (tmp_path / "out" / "bar" / "SKILL.md").exists()


def test_every_structural_reason_lands_in_one_report(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              Foo.md | # Foo\\n
              a
                dup.md | # A\\n
              b
                dup.md | # B\\n
              empty.md | \\n
              named.md | ---\\nname: named\\n---\\nbody\\n
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 1

    assert (tmp_path / "out" / "documator-errors.md").read_text() == snapshot("""\
# documator errors

- Foo.md: "Foo" is not a valid skill name
- the name "dup" is claimed by a/dup.md and b/dup.md
- empty.md (empty): the template is empty
- named.md (named): the template declares name, which the compiler sets
""")


def test_each_structural_reason_is_logged(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              Foo.md | # Foo\\n
            out
        """),
    )

    with caplog.at_level(logging.ERROR, logger="documator"):
        assert _skills(tmp_path / "in", tmp_path / "out") == 1

    assert caplog.messages == snapshot(
        [
            'Foo.md: "Foo" is not a valid skill name',
            "1 file, 0 warnings, 1 error",
            'Foo.md: "Foo" is not a valid skill name',
        ]
    )


def test_an_operational_failure_still_outranks_a_structural_one(tmp_path: Path) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              Foo.md | # Foo\\n
              bar.md | ![[Missing]]
            out
        """),
    )

    assert _skills(tmp_path / "in", tmp_path / "out") == 2


def test_logs_each_compiled_skill(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    build_tree(
        tmp_path,
        TreeLayout("""
            in
              deep
                foo.md | # Foo\\n
            out
        """),
    )

    with caplog.at_level(logging.INFO, logger="documator"):
        assert _skills(tmp_path / "in", tmp_path / "out") == 0

    assert "compiled deep/foo.md into foo/SKILL.md" in caplog.text
